#ifndef OPENCVPROCESSOR_GLOBAL_H
#define OPENCVPROCESSOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OPENCVPROCESSOR_LIBRARY)
#  define OPENCVPROCESSORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPENCVPROCESSORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OPENCVPROCESSOR_GLOBAL_H
